"""
GitHub Pull Request service.

A Pull Request is created only after explicit human approval.
"""

from __future__ import annotations

import re
from typing import Optional

from backend.github.client import (
    GitHubClient,
    PullRequestResult,
)
from backend.graph.state import (
    AgentState,
    GitHubResult,
)


class PullRequestService:
    """
    Convert an approved AgentState into a GitHub Pull Request.
    """

    def __init__(
        self,
        github_client: GitHubClient,
    ):
        self.github_client = github_client

    @staticmethod
    def _safe_branch_name(
        user_request: str,
        run_id: str,
    ) -> str:
        text = user_request.lower()

        text = re.sub(
            r"[^a-z0-9]+",
            "-",
            text,
        )

        text = text.strip("-")

        if not text:
            text = "software-change"

        text = text[:50].rstrip("-")

        return (
            f"ai-engineer/"
            f"{text}-"
            f"{run_id[:8]}"
        )

    @staticmethod
    def _build_commit_message(
        state: AgentState,
    ) -> str:
        request = state.get(
            "user_request",
            "software change",
        ).strip()

        if not request:
            request = "software change"

        request = re.sub(
            r"\s+",
            " ",
            request,
        )

        if len(request) > 72:
            request = (
                request[:69].rstrip()
                + "..."
            )

        return f"feat: {request}"

    @staticmethod
    def _build_pr_title(
        state: AgentState,
    ) -> str:
        request = state.get(
            "user_request",
            "Software change",
        ).strip()

        if not request:
            request = "Software change"

        request = re.sub(
            r"\s+",
            " ",
            request,
        )

        if len(request) > 72:
            request = (
                request[:69].rstrip()
                + "..."
            )

        return request

    @staticmethod
    def _build_pr_body(
        state: AgentState,
        reviewer: str,
        comment: str,
    ) -> str:
        review_results = state.get(
            "review_results",
            {},
        )

        summary = review_results.get(
            "summary",
            "Code review completed.",
        )

        modified_files = state.get(
            "modified_files",
            [],
        )

        generated_files = state.get(
            "generated_files",
            [],
        )

        test_results = state.get(
            "test_results",
            {},
        )

        test_status = (
            "passed"
            if test_results.get(
                "success",
                False,
            )
            else "failed"
        )

        lines = [
            "## Automated Software Engineering Change",
            "",
            (
                "This Pull Request was generated by the "
                "Multi-Agent AI Software Engineering System."
            ),
            "",
            "### Requirement",
            "",
            state.get(
                "user_request",
                "Not provided.",
            ),
            "",
            "### Implementation",
            "",
            summary,
            "",
            "### Tests",
            "",
            f"Test status: **{test_status}**",
            "",
            "### Modified Files",
            "",
        ]

        if modified_files:
            lines.extend(
                f"- `{path}`"
                for path in modified_files
            )
        else:
            lines.append(
                "- None reported"
            )

        lines.extend(
            [
                "",
                "### Generated Files",
                "",
            ]
        )

        if generated_files:
            lines.extend(
                f"- `{path}`"
                for path in generated_files
            )
        else:
            lines.append(
                "- None reported"
            )

        lines.extend(
            [
                "",
                "### Human Approval",
                "",
                (
                    "Reviewer: "
                    f"{reviewer or 'Not specified'}"
                ),
                "",
                (
                    "Comment: "
                    f"{comment or 'Approved.'}"
                ),
            ]
        )

        return "\n".join(lines)

    def create_pr_from_approved_state(
        self,
        state: AgentState,
        run_id: str,
        reviewer: str = "",
        comment: str = "",
        files: Optional[list[str]] = None,
    ) -> GitHubResult:

        approval = state.get(
            "approval_result",
            {},
        )

        if not approval.get(
            "approved",
            False,
        ):
            return {
                "status": "blocked",
                "branch": "",
                "commit_sha": "",
                "pr_number": 0,
                "pr_url": "",
                "error": (
                    "GitHub PR creation requires "
                    "explicit human approval."
                ),
            }

        repository_path = state.get(
            "repository_path"
        )

        if not repository_path:
            return {
                "status": "failed",
                "branch": "",
                "commit_sha": "",
                "pr_number": 0,
                "pr_url": "",
                "error": "Repository path is missing.",
            }

        branch_name = self._safe_branch_name(
            state.get(
                "user_request",
                "software-change",
            ),
            run_id,
        )

        commit_message = (
            self._build_commit_message(
                state
            )
        )

        pr_title = self._build_pr_title(
            state
        )

        pr_body = self._build_pr_body(
            state,
            reviewer,
            comment,
        )

        try:
            self.github_client.create_branch(
                branch_name
            )

            self.github_client.stage_changes(
                files
            )

            status = self.github_client.get_status()

            if not status:
                return {
                    "status": "failed",
                    "branch": branch_name,
                    "commit_sha": "",
                    "pr_number": 0,
                    "pr_url": "",
                    "error": (
                        "No repository changes are "
                        "available to commit."
                    ),
                }

            commit_sha = (
                self.github_client.commit_changes(
                    commit_message
                )
            )

            self.github_client.push_branch(
                branch_name
            )

            pr: PullRequestResult = (
                self.github_client.create_pull_request(
                    branch_name=branch_name,
                    title=pr_title,
                    body=pr_body,
                )
            )

            return {
                "status": "created",
                "branch": pr.branch,
                "commit_sha": commit_sha,
                "pr_number": pr.number,
                "pr_url": pr.url,
                "error": "",
            }

        except Exception as exc:
            return {
                "status": "failed",
                "branch": branch_name,
                "commit_sha": "",
                "pr_number": 0,
                "pr_url": "",
                "error": str(exc),
            }


__all__ = [
    "PullRequestService",
]