"""
Code Review Agent.

Reviews the implementation produced by the Coder Agent after
the test suite passes.

The Code Review Agent does not modify repository files.
It only analyzes the implementation and returns a structured
review result.
"""

from __future__ import annotations

import json
import time

from backend.graph.state import AgentState
from backend.llm import (
    get_groq_client,
    get_model,
)
from backend.tools.filesystem import read_file


MAX_REVIEW_CONTEXT = 30_000
MAX_RETRIES = 2


CODE_REVIEW_SYSTEM_PROMPT = """
You are the Code Review Agent in an autonomous software engineering system.

Your job is to review code that has already been generated by the Coder
Agent and successfully passed the repository test suite.

Review the implementation for:

1. Correctness
2. Code quality
3. Maintainability
4. Architecture consistency
5. Error handling
6. Input validation
7. Security concerns
8. Unnecessary changes
9. Potential regressions
10. Test coverage

IMPORTANT RULES:

- Review the actual current repository files.
- Do not invent files.
- Do not invent errors.
- Do not modify any files.
- Do not write implementation code.
- Do not expose secrets.
- Never include .env.
- Keep the review specific and actionable.
- Tests have already passed, but passing tests do not automatically mean
  the implementation is correct.
- Review only the implementation relevant to the current request.

Return ONLY data matching the provided JSON schema.
Do not return Markdown.
"""


def normalize_path(path: str) -> str:
    """Normalize Windows paths to repository-relative POSIX-style paths."""

    return str(path).replace("\\", "/")


def build_review_context(
    state: AgentState,
) -> str:
    """
    Build review context from the actual current repository.

    The files are read from disk so the reviewer sees the final code
    produced by the Coder rather than stale pre-coding content.
    """

    repository_path = state.get(
        "repository_path"
    )

    if not repository_path:
        raise ValueError(
            "Repository path is missing."
        )

    files_to_review = []

    # Prefer files actually modified/generated by the Coder.
    for path in state.get(
        "generated_files",
        [],
    ):
        normalized = normalize_path(path)

        if (
            normalized
            and normalized != ".env"
            and normalized not in files_to_review
        ):
            files_to_review.append(normalized)

    for path in state.get(
        "modified_files",
        [],
    ):
        normalized = normalize_path(path)

        if (
            normalized
            and normalized != ".env"
            and normalized not in files_to_review
        ):
            files_to_review.append(normalized)

    # If no generated files are available, fall back to the files
    # from the implementation plan.
    if not files_to_review:

        for task in state.get(
            "plan",
            [],
        ):
            for path in task.get(
                "files_to_modify",
                [],
            ):
                normalized = normalize_path(path)

                if (
                    normalized
                    and normalized != ".env"
                    and normalized not in files_to_review
                ):
                    files_to_review.append(normalized)

            for path in task.get(
                "files_to_create",
                [],
            ):
                normalized = normalize_path(path)

                if (
                    normalized
                    and normalized != ".env"
                    and normalized not in files_to_review
                ):
                    files_to_review.append(normalized)

    if not files_to_review:
        raise ValueError(
            "No files are available for code review."
        )

    sections = []
    total_size = 0

    for relative_path in files_to_review:

        if total_size >= MAX_REVIEW_CONTEXT:
            break

        try:
            content = read_file(
                repository_path,
                relative_path,
            )

        except Exception as exc:
            raise ValueError(
                f"Unable to read file for review "
                f"{relative_path}: {exc}"
            ) from exc

        remaining = (
            MAX_REVIEW_CONTEXT
            - total_size
        )

        if len(content) > remaining:
            content = (
                content[:remaining]
                + "\n\n[REVIEW CONTEXT TRUNCATED]"
            )

        sections.append(
            f"""
FILE: {relative_path}

{content}
"""
        )

        total_size += len(content)

    return "\n".join(sections)


def build_code_review_schema() -> dict:
    """
    Native Groq strict JSON schema for the Code Review Agent.
    """

    return {
        "name": "code_review",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "overall_status": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "changes_requested",
                    ],
                },
                "summary": {
                    "type": "string",
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "severity": {
                                "type": "string",
                                "enum": [
                                    "low",
                                    "medium",
                                    "high",
                                    "critical",
                                ],
                            },
                            "category": {
                                "type": "string",
                            },
                            "file": {
                                "type": "string",
                            },
                            "description": {
                                "type": "string",
                            },
                            "recommendation": {
                                "type": "string",
                            },
                        },
                        "required": [
                            "severity",
                            "category",
                            "file",
                            "description",
                            "recommendation",
                        ],
                        "additionalProperties": False,
                    },
                },
                "strengths": {
                    "type": "array",
                    "items": {
                        "type": "string",
                    },
                },
                "security_concerns": {
                    "type": "array",
                    "items": {
                        "type": "string",
                    },
                },
            },
            "required": [
                "overall_status",
                "summary",
                "issues",
                "strengths",
                "security_concerns",
            ],
            "additionalProperties": False,
        },
    }


def validate_review_result(
    result: dict,
) -> dict:
    """Validate the structured Code Review response."""

    if not isinstance(
        result,
        dict,
    ):
        raise ValueError(
            "Code Review response must be a JSON object."
        )

    required_fields = {
        "overall_status",
        "summary",
        "issues",
        "strengths",
        "security_concerns",
    }

    missing = (
        required_fields
        - set(result.keys())
    )

    if missing:
        raise ValueError(
            "Code Review response is missing fields: "
            f"{sorted(missing)}"
        )

    if result["overall_status"] not in {
        "approved",
        "changes_requested",
    }:
        raise ValueError(
            "Invalid Code Review status."
        )

    if not isinstance(
        result["issues"],
        list,
    ):
        raise ValueError(
            "Code Review issues must be a list."
        )

    if not isinstance(
        result["strengths"],
        list,
    ):
        raise ValueError(
            "Code Review strengths must be a list."
        )

    if not isinstance(
        result["security_concerns"],
        list,
    ):
        raise ValueError(
            "Code Review security_concerns must be a list."
        )

    for issue in result["issues"]:

        if not isinstance(
            issue,
            dict,
        ):
            raise ValueError(
                "Each Code Review issue must be an object."
            )

        if issue.get("file") == ".env":
            raise ValueError(
                "Code Review cannot reference .env."
            )

    return result


def review_code(
    state: AgentState,
) -> dict:
    """Run the Code Review LLM."""

    repository_context = build_review_context(
        state
    )

    test_results = state.get(
        "test_results",
        {},
    )

    prompt = f"""
USER REQUIREMENT
================

{state.get("user_request", "")}

IMPLEMENTATION PLAN
===================

{json.dumps(
    state.get("plan", []),
    indent=2,
)}

FILES GENERATED
===============

{json.dumps(
    state.get("generated_files", []),
    indent=2,
)}

FILES MODIFIED
==============

{json.dumps(
    state.get("modified_files", []),
    indent=2,
)}

TEST RESULTS
============

{json.dumps(
    test_results,
    indent=2,
)}

CURRENT CODE
============

{repository_context}

Perform the code review now.

Remember:
- Tests have passed.
- Review the actual implementation.
- Do not modify files.
- Return ONLY the required JSON object.
"""

    last_error = None

    for attempt in range(
        1,
        MAX_RETRIES + 1,
    ):

        try:

            client = get_groq_client()

            response = client.chat.completions.create(
                model=get_model(),
                messages=[
                    {
                        "role": "system",
                        "content": CODE_REVIEW_SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ],
                temperature=0,
                reasoning_effort="low",
                max_tokens=12000,
                response_format={
                    "type": "json_schema",
                    "json_schema": build_code_review_schema(),
                },
            )

            if not response.choices:
                raise ValueError(
                    "Code Review received no response choices."
                )

            content = response.choices[0].message.content

            if not content:
                raise ValueError(
                    "Code Review returned an empty response."
                )

            result = json.loads(
                content
            )

            return validate_review_result(
                result
            )

        except Exception as exc:

            last_error = exc

            if attempt < MAX_RETRIES:
                time.sleep(
                    2 * attempt
                )

    raise RuntimeError(
        "Code Review failed after "
        f"{MAX_RETRIES} attempts: {last_error}"
    )


def code_review_agent(
    state: AgentState,
) -> AgentState:
    """
    Execute the Code Review Agent.

    The review runs only after successful tests.
    """

    test_results = state.get(
        "test_results",
        {},
    )

    if not test_results.get(
        "success",
        False,
    ):
        return {
            **state,
            "review_results": {
                "overall_status": "changes_requested",
                "summary": (
                    "Code review skipped because "
                    "tests did not pass."
                ),
                "issues": [],
                "strengths": [],
                "security_concerns": [],
            },
            "errors": [
                *state.get("errors", []),
                "Code Review requires passing tests.",
            ],
            "current_step": "code_review_failed",
        }

    try:

        review_result = review_code(
            state
        )

        return {
            **state,
            "review_results": review_result,
            "current_step": "code_review_complete",
        }

    except Exception as exc:

        return {
            **state,
            "review_results": {},
            "errors": [
                *state.get("errors", []),
                f"Code Review Agent error: {exc}",
            ],
            "current_step": "code_review_failed",
        }
