"""
Code Review Agent.

Reviews the code generated by the Coder Agent after tests pass.
The agent does not modify repository files.
"""

import json
import time

from backend.graph.state import AgentState
from backend.llm import get_groq_client, get_model
from backend.tools.filesystem import read_file


MAX_REVIEW_CONTEXT = 30_000
MAX_RETRIES = 2


CODE_REVIEW_SYSTEM_PROMPT = """
You are a senior software engineer performing a final code review.

Your job is to review the actual code currently present in the repository
after implementation and testing.

Review the implementation for:

1. Correctness
2. Code quality
3. Maintainability
4. Architecture consistency
5. Error handling
6. Input validation
7. Security
8. Unnecessary changes
9. Possible regressions
10. Test coverage

Important rules:

- Review the actual current files.
- Do not modify files.
- Do not generate implementation code.
- Do not invent files.
- Do not request changes to files that are unrelated to the user request.
- Never request access to .env.
- Never expose secrets.
- Consider the existing repository architecture.
- Consider the original user requirement.
- Consider the test results.
- Be precise and technically justified.

Set overall_status to:

"approved"
    when the implementation is acceptable and no required changes remain.

"changes_requested"
    when there are important problems that should be fixed before approval.

Return ONLY valid JSON matching the supplied schema.
"""


def normalize_path(path: str) -> str:
    """
    Normalize Windows/Linux repository paths.
    """
    return path.replace("\\", "/").strip()


def build_review_context(
    state: AgentState,
) -> str:
    """
    Build the code context that will be sent to the review model.
    """

    repository_path = state.get(
        "repository_path"
    )

    if not repository_path:
        return "No repository path was provided."

    generated_files = [
        normalize_path(path)
        for path in state.get(
            "generated_files",
            [],
        )
    ]

    modified_files = [
        normalize_path(path)
        for path in state.get(
            "modified_files",
            [],
        )
    ]

    plan = state.get(
        "plan",
        [],
    )

    planned_files = []

    for task in plan:
        for path in task.get(
            "files_to_modify",
            [],
        ):
            planned_files.append(
                normalize_path(path)
            )

        for path in task.get(
            "files_to_create",
            [],
        ):
            planned_files.append(
                normalize_path(path)
            )

    candidate_files = (
        generated_files
        + modified_files
        + planned_files
    )

    unique_files = []

    for path in candidate_files:
        if not path:
            continue

        if path == ".env":
            continue

        if path not in unique_files:
            unique_files.append(path)

    if not unique_files:
        return "No implementation files were identified for review."

    sections = []
    total_size = 0

    for relative_path in unique_files:
        if total_size >= MAX_REVIEW_CONTEXT:
            break

        try:
            content = read_file(
                repository_path,
                relative_path,
            )
        except Exception as exc:
            sections.append(
                f"FILE: {relative_path}\n"
                f"[Unable to read file: {exc}]"
            )
            continue

        remaining = (
            MAX_REVIEW_CONTEXT
            - total_size
        )

        if len(content) > remaining:
            content = (
                content[:remaining]
                + "\n\n[FILE CONTEXT TRUNCATED]"
            )

        section = (
            f"FILE: {relative_path}\n"
            f"{'=' * 60}\n"
            f"{content}\n"
        )

        sections.append(section)
        total_size += len(content)

    return "\n".join(sections)


def build_code_review_schema() -> dict:
    """
    Strict JSON schema for the Groq structured response.
    """

    return {
        "name": "code_review",
        "strict": True,
        "schema": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "overall_status": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "changes_requested",
                    ],
                },
                "summary": {
                    "type": "string",
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "severity": {
                                "type": "string",
                            },
                            "category": {
                                "type": "string",
                            },
                            "file": {
                                "type": "string",
                            },
                            "description": {
                                "type": "string",
                            },
                            "recommendation": {
                                "type": "string",
                            },
                        },
                        "required": [
                            "severity",
                            "category",
                            "file",
                            "description",
                            "recommendation",
                        ],
                    },
                },
                "strengths": {
                    "type": "array",
                    "items": {
                        "type": "string",
                    },
                },
                "security_concerns": {
                    "type": "array",
                    "items": {
                        "type": "string",
                    },
                },
            },
            "required": [
                "overall_status",
                "summary",
                "issues",
                "strengths",
                "security_concerns",
            ],
        },
    }


def validate_review_result(
    result: dict,
) -> None:
    """
    Validate the review result before storing it in AgentState.
    """

    if not isinstance(result, dict):
        raise ValueError(
            "Code review response must be a JSON object."
        )

    required_fields = {
        "overall_status",
        "summary",
        "issues",
        "strengths",
        "security_concerns",
    }

    missing = required_fields - set(
        result.keys()
    )

    if missing:
        raise ValueError(
            "Code review response is missing fields: "
            + ", ".join(sorted(missing))
        )

    if result["overall_status"] not in {
        "approved",
        "changes_requested",
    }:
        raise ValueError(
            "Invalid code review status."
        )

    if not isinstance(
        result["summary"],
        str,
    ):
        raise ValueError(
            "Code review summary must be a string."
        )

    if not isinstance(
        result["issues"],
        list,
    ):
        raise ValueError(
            "Code review issues must be a list."
        )

    if not isinstance(
        result["strengths"],
        list,
    ):
        raise ValueError(
            "Code review strengths must be a list."
        )

    if not isinstance(
        result["security_concerns"],
        list,
    ):
        raise ValueError(
            "Code review security concerns must be a list."
        )

    for issue in result["issues"]:
        if not isinstance(
            issue,
            dict,
        ):
            raise ValueError(
                "Each review issue must be an object."
            )

        required_issue_fields = {
            "severity",
            "category",
            "file",
            "description",
            "recommendation",
        }

        missing_issue_fields = (
            required_issue_fields
            - set(issue.keys())
        )

        if missing_issue_fields:
            raise ValueError(
                "Review issue is missing fields: "
                + ", ".join(
                    sorted(missing_issue_fields)
                )
            )

        issue_file = normalize_path(
            str(issue.get("file", ""))
        )

        if (
            issue_file == ".env"
            or issue_file.endswith("/.env")
            or "/.env/" in issue_file
        ):
            raise ValueError(
                "Code review cannot reference .env."
            )


def review_code(
    state: AgentState,
) -> dict:
    """
    Send the current implementation to Groq for review.
    """

    client = get_groq_client()
    model = get_model()

    user_request = state.get(
        "user_request",
        "",
    )

    plan = state.get(
        "plan",
        [],
    )

    test_results = state.get(
        "test_results",
        {},
    )

    architecture_summary = state.get(
        "architecture_summary",
        "",
    )

    repository_context = build_review_context(
        state
    )

    prompt = f"""
USER REQUIREMENT
================
{user_request}

REPOSITORY ARCHITECTURE
=======================
{architecture_summary}

IMPLEMENTATION PLAN
===================
{json.dumps(plan, indent=2)}

TEST RESULTS
============
{json.dumps(test_results, indent=2)}

GENERATED FILES
===============
{json.dumps(state.get("generated_files", []), indent=2)}

MODIFIED FILES
==============
{json.dumps(state.get("modified_files", []), indent=2)}

CURRENT IMPLEMENTATION
======================
{repository_context}

Perform the final code review.

Approve the implementation only if no required changes remain.
"""

    schema = build_code_review_schema()

    last_error = None

    for attempt in range(
        MAX_RETRIES
    ):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {
                        "role": "system",
                        "content": CODE_REVIEW_SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ],
                temperature=0,
                max_tokens=10_000,
                response_format={
                    "type": "json_schema",
                    "json_schema": schema,
                },
            )

            content = (
                response.choices[0]
                .message
                .content
            )

            if not content:
                raise ValueError(
                    "Code review returned an empty response."
                )

            result = json.loads(
                content
            )

            validate_review_result(
                result
            )

            return result

        except Exception as exc:
            last_error = exc

            if attempt < MAX_RETRIES - 1:
                time.sleep(
                    2 * (attempt + 1)
                )

    raise RuntimeError(
        f"Code review failed: {last_error}"
    )


def code_review_agent(
    state: AgentState,
) -> AgentState:
    """
    Code Review Agent.

    Runs only after tests pass.
    """

    test_results = state.get(
        "test_results",
        {},
    )

    if not test_results.get(
        "success",
        False,
    ):
        return {
            **state,
            "review_results": {
                "overall_status": "changes_requested",
                "summary": (
                    "Code review was skipped because "
                    "the test suite did not pass."
                ),
                "issues": [],
                "strengths": [],
                "security_concerns": [],
            },
            "current_step": "code_review_skipped",
        }

    try:
        review_result = review_code(
            state
        )

        return {
            **state,
            "review_results": review_result,
            "current_step": "code_review_complete",
        }

    except Exception as exc:
        return {
            **state,
            "review_results": {
                "overall_status": "changes_requested",
                "summary": (
                    "Code review failed to execute."
                ),
                "issues": [],
                "strengths": [],
                "security_concerns": [],
            },
            "errors": [
                *state.get("errors", []),
                f"Code Review Agent error: {exc}",
            ],
            "current_step": "code_review_failed",
        }